# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chromatin_regulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensembl_id', models.CharField(max_length=50)),
                ('gene_symbol', models.CharField(max_length=10)),
                ('function', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('genecards_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
