# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromatin_regulators',
            name='gene_symbol',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
